### ISSUE TITLE
CUDA related error

### ISSUE THREAD

**Issue by Starbucksmax** [LLNL/LEAP#55]
When I use ASD-POCS using my data. Some cuda-related  error happen.
The forward projection and FBP works.  I'm using LEAP  v1.13
In Linux the error is 
```
  File "/home/exouser/stefen/code/DDS/physics/multileap4GPU.py", line 44, in IR
    leapct.ASDPOCS(proj,rec,iter_num,10,10,filters)
  File "/home/exouser/.local/lib/python3.10/site-packages/leapctype.py", line 2971, in ASDPOCS
    P1[P1==0.0] = 1.0
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
In Windows, the error is
```
  File "D:\code\improved diffusion\DDS\physics\multileap4GPU.py", line 44, in IR
    leapct.ASDPOCS(proj,rec,iter_num,10,10,filters)
  File "C:\Users\Shuo_Han\AppData\Local\anaconda3\envs\diff\lib\site-packages\leapctype.py", line 2987, in ASDPOCS
    Pf_minus_g = self.allocateData(g)
  File "C:\Users\Shuo_Han\AppData\Local\anaconda3\envs\diff\lib\site-packages\leapctype.py", line 1429, in allocateData
    y = torch.zeros([x.shape[0], x.shape[1], x.shape[2]], dtype=torch.float32, device=torch.device('cuda:'+str(self.get_gpu())))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by kylechampley** [comment]
It looks like you are running out of memory.  When I first wrote this algorithm, I did not spend a lot of time figuring out how to use as little memory as possible.  I'll go back through this code and see if I can use fewer data structures and/or reuse some.

In addition, when the data structures "live" on the CPU and LEAP just copies them back and forth to the GPU, I make sure I split up the data into small enough chunks so that I don't run out of GPU memory, but I see that you are using the feature where the data lives on the GPU.  In this case, torch is allocating a lot of GPU memory that I don't really have control of and that is why I think this is a GPU memory issue.

Anyway, like I said, I'll do through this algorithm and see if I can use less memory.  Just out of curiosity, what is the size of your CT projections and CT volume?

**Comment by Starbucksmax** [comment]
Well, I don't think it will out-of-memory. Cause I'm using the A100-40GB.
FYI, the size of projection is (240,1,835), CT volume is (1,256,256).
Previously it worked on my last project. This time didn't work.
And sometimes when I set the wrong configurations like project the 256*256 image and reconstruct it by 512*512, it will cause this problem too. But this time the geometry is correct. I don't know why.

**Comment by kylechampley** [comment]
Ya, you’re probably right that this is not a memory issue. Please update to v1.14. There was a bug in the subsets partition that was solved in this release.

**Comment by Starbucksmax** [comment]
I've figured it out. The initial image for the iterative alg involves a 4-dimensional tensor. By squeezing it down to 3 dimensions, the problem is resolved. I suggest adding an error tracker to better identify the actual bug. lol
